### ISSUE TITLE
problem with making a playlist---

### ISSUE THREAD

**Issue by mikegamer2064** [robobeaver6/plex_playlist_generator#3]
for of all when i downlaoded your script i got a bunch of f' before a lot of lines... a little mistake you should check..

for  example: ` if show.title in BLACKLIST:
            logger.debugf('GET_EPISODES: Show Blacklisted: {show.title}')
            continue`

see the f before GET EPISODES there  alomst 10 lines like that that break your script...

but the main problem is when i made your script i got everything seems to work but then:
i got this: TypeError: 

`Traceback (most recent call last):
  File "C:\plex_playlist_generator\playlist_generator.py", line 165, in <module>
    main()
  File "C:\plex_playlist_generator\playlist_generator.py", line 149, in main
    episodes = get_random_episodes(all_shows, n=args.number)
  File "C:\plex_playlist_generator\playlist_generator.py", line 77, in get_random_episodes
    if skipped_missing(all_shows.get(title=show_name), show_episodes[show_name][0]):
  File "C:\plex_playlist_generator\playlist_generator.py", line 108, in skipped_missing
    show.get(season=episode.seasonNumber, episode=episode.index-1)
TypeError: unsupported operand type(s) for -: 'str' and 'int'`

help me plz i need that program to work

thank you for your works.

**Comment by mikegamer2064** [comment]
its fine now... it was a probleme with my plexapi and the tvdb_api.
